services:
  shell:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: shell
    ports:
      - "4200:80"
    restart: always

  remote-home:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: remote-home
    ports:
      - "4201:80"
    restart: always

  remote-about:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: remote-about
    ports:
      - "4202:80"
    restart: always

  remote-profile:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: remote-profile
    ports:
      - "4203:80"
    restart: always
