FROM nginx:1.25-alpine

# xóa config mặc định
RUN rm /etc/nginx/conf.d/default.conf

# config serve static Angular
RUN printf "server {\n\
    listen 8081;\n\
    server_name _;\n\
\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
\n\
    location / {\n\
        try_files \$uri \$uri/ /index.html;\n\
    }\n\
}\n" > /etc/nginx/conf.d/default.conf

# copy artefact đã build sẵn
COPY dist/shell/browser/ /usr/share/nginx/html/

EXPOSE 8081
CMD ["nginx", "-g", "daemon off;"]
