version: "3.9"

services:
  shell:
    build: docker/shell
    expose:
      - "8081"

  remote-home:
    build: docker/remote-home
    expose:
      - "8082"

  remote-about:
    build: docker/remote-about
    expose:
      - "8083"

  remote-profile:
    build: docker/remote-profile
    expose:
      - "8084"

  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - shell
      - remote-home
      - remote-about
      - remote-profile
