FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf

RUN printf "server {\n\
    listen 8083;\n\
    server_name _;\n\
\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
\n\
    location / {\n\
        try_files \$uri \$uri/ /index.html;\n\
    }\n\
}\n" > /etc/nginx/conf.d/default.conf

COPY dist/remote-about/browser/ /usr/share/nginx/html/

EXPOSE 8083
CMD ["nginx", "-g", "daemon off;"]
