events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /shell/browser/index.html;
        }

        location /remote-home/ {
            try_files $uri $uri/ /remote-home/browser/index.html;
        }

        location /remote-about/ {
            try_files $uri $uri/ /remote-about/browser/index.html;
        }

        location /remote-profile/ {
            try_files $uri $uri/ /remote-profile/browser/index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff2?)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
