events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    # ===== SHELL =====
    location = / {
      rewrite ^ /browser/index.html last;
    }

    location /browser/ {
      try_files $uri =404;
    }

    # ===== REMOTE HOME =====
    location /remote-home/ {
      rewrite ^/remote-home/?(.*)$ /remote-home/browser/index.html last;
    }

    location /remote-home/browser/ {
      try_files $uri =404;
    }

    # ===== REMOTE ABOUT =====
    location /remote-about/ {
      rewrite ^/remote-about/?(.*)$ /remote-about/browser/index.html last;
    }

    location /remote-about/browser/ {
      try_files $uri =404;
    }

    # ===== REMOTE PROFILE =====
    location /remote-profile/ {
      rewrite ^/remote-profile/?(.*)$ /remote-profile/browser/index.html last;
    }

    location /remote-profile/browser/ {
      try_files $uri =404;
    }

    # ===== STATIC CACHE =====
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff2?)$ {
      expires 1y;
      add_header Cache-Control "public, immutable";
    }
  }
}
