FROM nginx:1.25-alpine

RUN rm -f /etc/nginx/conf.d/default.conf
COPY projects/shell/nginx.conf /etc/nginx/conf.d/default.conf

COPY dist/shell/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
