FROM nginx:1.25-alpine

RUN rm -f /etc/nginx/conf.d/default.conf
COPY projects/remote-about/nginx.conf /etc/nginx/conf.d/default.conf

COPY dist/remote-about/browser /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
