server {
    listen 80;
    server_name _;

    gzip on;
    gzip_comp_level 6;
    gzip_min_length 1024;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript;


    location /api/auth-service/ {

            proxy_pass https://agentbanking.bbtech.io.vn/api/auth-service/;

            proxy_http_version 1.1;

            # SSL settings khi proxy HTTPS
            proxy_ssl_server_name on;
            proxy_ssl_verify off;

            proxy_set_header Host agentbanking.bbtech.io.vn;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            client_max_body_size 10m;
        }

    location / {
        proxy_pass http://shell:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /remote-home/ {
        proxy_pass http://remote-home:8082/;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /remote-about/ {
        proxy_pass http://remote-about:8083/;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /remote-profile/ {
        proxy_pass http://remote-profile:8084/;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
