server {
    listen 80;

    # Shell (app chính)
    location / {
        proxy_pass http://shell:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Remote Home
    location /remote-home/ {
        proxy_pass http://remote-home:80/;
    }

    # Remote About
    location /remote-about/ {
        proxy_pass http://remote-about:80/;
    }

    # Remote Profile
    location /remote-profile/ {
        proxy_pass http://remote-profile:80/;
    }
}
