server {
    listen 80;

    # Serve shell static files
    location / {
        alias /usr/share/nginx/html/shell/;
        try_files $uri $uri/ /index.html;
    }

    # Serve remote-home static files
    location /remote-home/ {
        alias /usr/share/nginx/html/remote-home/;
        try_files $uri $uri/ /remote-home/index.html;
    }

    # Serve remote-about static files
    location /remote-about/ {
        alias /usr/share/nginx/html/remote-about/;
        try_files $uri $uri/ /remote-about/index.html;
    }

    # Serve remote-profile static files
    location /remote-profile/ {
        alias /usr/share/nginx/html/remote-profile/;
        try_files $uri $uri/ /remote-profile/index.html;
    }
}
